	</div><!-- <div id="coverPage" class="initialPage"> -->
	<script type="text/javascript">var static_server='<?php echo DOMAIN ?>webcreathtml/';</script>
	<script type="text/javascript"
		src="<?php echo DOMAIN ?>webcreathtml/js/obfs/alatca.package.basic.1-1-81.js?error=0&amp;lang=en"></script>
	<script type="text/javascript"
		src="<?php echo DOMAIN ?>webcreathtml/js/media/en.type1.1.12.js"></script>
	<script type="text/javascript">Event.observe($('watchVideo'), 'click', function () {Lightbox.AlatcaVideo('<div id="watchVideoClose" class="lightBoxClose" onclick="Lightbox.close();"><!-- --></div><object width="660" height="405"><param name="wmode" value="transparent"></param><param name="movie" value="http://www.youtube.com/v/fP1YKbhIhUE?fs=1&amp;hl=cs_CZ&amp;rel=0&amp;hd=1&amp;border=1"></param><param name="allowFullScreen" value="true"></param><param name="allowscriptaccess" value="always"></param><embed src="http://www.youtube.com/v/fP1YKbhIhUE?fs=1&amp;hl=cs_CZ&amp;rel=0&amp;hd=1&amp;border=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="660" height="405" wmode="transparent"></embed></object>');Lightbox.open('videoPlayer');_gaq.push(['t2._trackEvent','Video','OpenVideo']);});SignUp.projectCheckUrl='http%3A%2F%2Fwww.Alatca.com%2Fcheck-project-name%2F';SignUp.messages={available:'available!',notAvailable:'not available',unavailableName:'This project address has already been taken!',bannedName:'The website name contains inappropriate or obscene words.',invalidName:'Please use only lower case letters, numbers or a dash!<p>Example: <strong>lovelyjohn</strong></p>',shortName:'The project address must have at least 3 characters.',longName:'The project address can have up to 32 characters.',invalidEmail:'Invalid email address!',invalidPassword:'The password must have at least 6 characters!',samePassword:'The project address and your password mustn\'t be the same!',loadingInfo:'<h2>Please wait!</h2><p>Your website is being configured...</p>',loadingImg:'<?php echo DOMAIN ?>webcreathtml/img/layout3-1/signupLoading.gif'};SignUpTracker.enabled = true;SignUpTracker.data.steps.page = 1;SignUpTracker.data.steps.form = 1;var a=new Element('input', {'type':'hidden','name':'aa62a6988a6','value':'2f0785f6f9'});$('rbcSystemFnc').appendChild(a);SimpleMenu.addMenuControl({button:'loginLinkBtn',id:'headerSignIn',dir:'up',top:21});SimpleMenu.addMenuControl({button:'changeLanguage',id:'languagesList',dir:'bottom'});SimpleMenu.toggleElement('hideLanguages', 'language_list');SimpleMenu.toggleElement('showLanguages', 'language_list');SimpleMenu.addMenuControl({button:'languageListMore',id:'aMoreLangs',dir:'up',noChangeStyle:true});SimpleMenu.addMenuControl({button:'aMore',id:'aMorePages',dir:'up',noChangeStyle:true});</script>
	<div id="stats"></div>
</body>
</html>