BranchTypes.data = {
	ACCOUNTANT_TAX_SERVICES: "Kế toán / Dịch vụ thuế",
	ADVERTISING_AGENCY: "Quảng cáo",
	AMUSEMENT_RECREATION: "Giải trí / Tro choi (Bowling, Billiards, Arcades)",
	ANTIQUES_STORE: "Đồ cổ",
	ARCHITECTURAL_FIRM: "Architectural Firm",
	ARTIST_DESIGNER: "Artist / Designer",
	BABYSITTING: "Babysitting",
	BAKERY_PASTRY_SHOP: "Bakery / Pastry Shop",
	BAND_CHOIR_MUSIC_CLUB: "Band / Choir / Music Club",
	BEAUTY_NAIL_SALONS: "Beauty &amp; Nail Salons",
	BEAUTY_HAIR_SALONS: "Beauty / Hair Salons &amp; Barbershops",
	BICYCLE_SHOP: "Bike Shop",
	BOOKSTORE: "Bookstore",
	BREEDER: "Breeder",
	CAFE_BAR: "Café / Bar",
	AUTO_CAR_BODY_REPAIR_SHOP: "Car Body Repair Shop",
	AUTO_CAR_DEALERSHIP: "Car Dealership",
	CARPENTER_FRAMING_CONTRACTORS: "Carpenter / Framing Contractors",
	CATERING_SERVICES: "Catering Services",
	CHIROPRACTOR_OSTEOPATH: "Chiropractor / Osteopath",
	CLEANING_SERVICES: "Cleaning Services",
	CLUBS_ASSOCIATIONS: "Clubs / Associations",
	COMPUTER_STORE: "Computer Store",
	CONSULTING_GROUP: "Consulting Group",
	CONTRACTORS: "Contractors",
	COURIER_SERVICES: "Courier Services",
	DENTIST: "Dentist",
	DEVELOPER_CONSTRUCTION_COMPANY: "Developer / Construction Company",
	DOCTOR: "Doctor",
	DRIVING_SCHOOL: "Driving School",
	ELECTRICIAN_ELECTRICAL_CONTRACTORS: "Electrician / Electrical Contractors",
	ELECTRONICS_ELECTRICAL_APPLIANCES: "Electronics / Electrical Appliances",
	EVENT_PLANNING: "Event Planning (Wedding / Party / Corporate)",
	FAITH_BASED_ORGANIZATIONS: "Faith-based Organizations",
	FARMERS_MARKETS: "Farmers Markets / Small Growers",
	FASHION_CLOTHING_STORE: "Fashion / Clothing Store",
	FLORIST_FLOWER_SHOP: "Florist / Flower Shop",
	FUNERAL_HOMES: "Funeral Homes",
	FURNITURE_STORE: "Furniture Store",
	GARDENING_LANDSCAPING: "Gardening / Landscaping",
	GENERIC_BUSINESS_TYPE: "Generic Business Type",
	GLASS_AND_GLAZING_CONTRACTORS: "Glass and Glazing Contractors",
	GOODS_TRANSPORTION_HAULING: "Goods Transportion &amp; Hauling",
	GROCER_GROCERY: "Grocer / Grocery",
	GYM_FITNESS_SPORTS_CENTERS: "Gym / Fitness / Recreational Sports Centers",
	HARDWARE_STORES: "Hardware Stores",
	HVAC_SERVICES: "Heating, Ventilation &amp; Air Conditioning (HVAC) Services",
	HOME_DECOR_ACCESSORIES: "Home Decor &amp; Accessories",
	HOME_IMPROVEMENT_BUILDING_SUPPLIES: "Home Improvement / Building Supplies",
	HOMEOWNERS_ASSOCIATION: "Homeowners' Association",
	HOTEL: "Hotel",
	HUMAN_RESOURCES: "Human Resources",
	INSURANCE_SERVICES: "Insurance Services",
	INTERIOR_DESIGN_RENOVATIONS: "Interior Design / Renovations",
	INVESTMENT_ADVISER: "Investment Adviser",
	IT_CONSULTING_SERVICES: "IT Consulting / Services",
	JEWELER: "Jeweler",
	KINDERGARTEN: "Kindergarten",
	LAUNDRY_CLEANING_IRONING_SERVICES: "Laundry / Dry Cleaning / Ironing Services",
	LAW_OFFICE_NOTARY: "Law Office / Notary",
	LIBRARY: "Library",
	LOCKSMITH: "Locksmith",
	CHILDCARE: "Medical Services",
	MOTORCYCLE_SHOP: "Motorcycle Shop",
	MOVING_STORAGE_SERVICES: "Moving / Storage Services",
	NIGHTCLUB_DISCO: "Nightclub / Disco",
	NON_PROFIT_ORGANIZATIONS: "Non-profit Organizations",
	OPTICIAN: "Optician",
	OTHER_BUSINESS_SERVICES: "Other Business Services",
	OTHER_EDUCATIONAL_SERVICES: "Other Educational Services",
	PAINTER_PAPERHANGER: "Painter / Paperhanger",
	PET_CARE: "Pet Care (Pet Grooming / Walking Services)",
	PHARMACY: "Pharmacy",
	PHOTOGRAPHY: "Photography Studio",
	PHYSIOTHERAPIST_MASSEUSE: "Physiotherapist / Masseuse",
	PLUMBER: "Plumber / Plumbing Contractors",
	PR_MARKETING: "PR / Marketing / Communications Services",
	PRINTING_SERVICES: "Printing / Duplication Services",
	REAL_ESTATE: "Real Estate Agent / Broker",
	RESTAURANT: "Restaurant",
	RETIREMENT_HOMES: "Retirement Homes",
	ROOFER: "Roofer / Roofing Contractors",
	SCHOOL_COLLEGE: "School / College / University",
	SHOE_STORE: "Shoe store",
	SPA_BEAUTY: "Spa / Beauty Treatments",
	SPORTS_OUTDOOR: "Sports / Outdoor Equipment Store",
	SPORTS_CLUBS: "Sports Clubs / Associations / Leagues",
	STATIONERY: "Stationery / Office Supply",
	TAILORING: "Tailoring / Alteration Services",
	TAXI_LIMO: "Taxi, Limo, Chartered Transportation Services",
	TOY_STORE: "Toy Store",
	TRAVEL: "Travel Agencies",
	VETERINARIANS: "Veterinarians",
	WEB_DESIGN: "Web Design",
	WEB_DEVELOPMENT: "Web Development"
};

BranchTypes.keywords = {
	ACCOUNTANT_TAX_SERVICES: "accountant, accountant services, tax services, Taxes, tax advice, tax consulting, IRS refund, tax returns, tax accountant,  filing taxes, accounting, bookkeeping",
	ADVERTISING_AGENCY: "advertising agency, advertising, Advertising services, Promotion campaign, Marketing consultant, Print creative, promotional items, sales promotion, graphic design, PR, public relations, social media, email marketing, online marketing, web design",
	AMUSEMENT_RECREATION: "amusement center, recreation center, amusement, recreation, bowling, bowling lane, table tennis, golf simulator, pool, business parties, birthday parties, kids party, entertainment, fun activities, mini golf",
	ANTIQUES_STORE: "antiques, antiques store, gold and silver coins, medals, investment gold, antiques, collectibles, paintings, drawings, prints, jewelry, watches, sculptures, art glass",
	ARCHITECTURAL_FIRM: "architectural firm, architect, house plan, house blueprint, Apartment blueprint, Housing, Design, Architect, Architecture, house plan, apartment plan, architectural design",
	ARTIST_DESIGNER: "artist, designer, design, people portraits, paintings, sketches, drawings, portraits from photographs, photos, creative design",
	BABYSITTING: "Babysitting, babysitting agency, babysitter, babysitting in group, weekend sitting",
	BAKERY_PASTRY_SHOP: "bakery, pastry shop, Cake, bread, sandwiches, cookies, bread rolls, birthday cake, muffins, cup cakes, coffee cake, chocolate cake, icing cake, wedding cake, fresh bread, desserts",
	BAND_CHOIR_MUSIC_CLUB: "band, choir, music club, Rock band, vocals, vocalist, guitar, bass, music, band CD club, soloist, band concerts, band performance, wedding band, live band, live music",
	BEAUTY_NAIL_SALONS: "Beauty salon, nail salon, manicure, women manicure, men manicure, French manicure, acrylic nails, Nails, Salon, Fashion nails, Model, nail polish, nail style",
	BEAUTY_HAIR_SALONS: "Hair salon, hair color, hair conditioning, haircut, hair style, hair highlights, conditioning treatment, hairstyle, salon, hair fashion",
	BICYCLE_SHOP: "Bicycle shop, bicycle service, Bike, Cycling,  bike Service, bike Repair, bike Rental, bike Sales, Sporting Goods",
	BOOKSTORE: "bookstore, bookshop, Books, coffee shop, book reading, book club, Literature",
	BREEDER: "Breeder, breeding station, dogs, cats, animals, puppies, kittens, cubs, young animals, youngs",
	CAFE_BAR: "cafe-bar, cafe, bar, Coffee, Hot Chocolate, Beer, Wine, coffee place, coffee shop, Tea, waiter, waitress, Cafe / Bar",
	AUTO_CAR_BODY_REPAIR_SHOP: "car repair shop, car body repair shop, Automobile, repair, service, winter tires, summer tires, car maintenance, car tune-up, breaks service, car service, radiator service",
	AUTO_CAR_DEALERSHIP: "car dealer, car dealership, Car sales, new cars, new car, test drive, used car, dealer service, car upgrade, used car dealer",
	CARPENTER_FRAMING_CONTRACTORS: "Woodcraft, carpenter, framing contractor, cabinetry, cabinet making, custom cabinets, chairs, beds, Artisan furniture, antique furniture restoration, construction scaffolding, cabins, vacation home construction, home repair",
	CATERING_SERVICES: "catering, catering services, food catering, special occasion food service, wedding menu and food service, catering,  food ordering, Health Food, food delivery",
	CHIROPRACTOR_OSTEOPATH: "chiropractor, osteopath, spine problems, spine pain,  back pain, back massage, back pain, muscle relaxation, pain in the neck, spinal manipulation, back adjustments, muscle spasm",
	CLEANING_SERVICES: "cleaning service, House Cleaning, home cleaning service, office cleaning service, window cleaning, carpet cleaning, cleaning services for businesses, general cleaning, post-construction cleaning, cleaning house inspection",
	CLUBS_ASSOCIATIONS: "club, association, Independent associations, teenage clubs, extracurricular activities,  interest group, expert club, meet up, training, meetings",
	COMPUTER_STORE: "computer store, Shop computers, computing, electronics, laptops, computers, components, peripherals, LCD TV, Digital Cameras",
	CONSULTING_GROUP: "consulting, consulting group, business consulting, management consulting, business strategy, project management, business plan, start-up companies, management courses,  financial courses, legal assistance",
	CONTRACTORS: "contractors, home building, home repair, fixer upper, foreclosure repair, floor construction, flooring, tile, hardwood installation, painting, bathroom remodel, kitchen remodel, renovation of bathrooms, renovation of residential interiors, insulation, facades, roof repair, reconstruction, color mixing, thermal insulation, home remodel advice, remodel project quote",
	COURIER_SERVICES: "courier services, mail delivery, expedite, courier service, same day delivery, next day delivery, transportation, fast delivery, food delivery, flower delivery, domestic transport, express courier, international transport",
	DENTIST: "dentist, dental care, tooth implants, aesthetic dental treatment, cosmetic dentistry, dental hygiene, teeth whitening, comfort, tooth X-ray, dental laboratory, tooth ache, tooth implants, crown, kids dentist",
	DEVELOPER_CONSTRUCTION_COMPANY: "developer, construction company, home builder, house builder, construction company, family houses, apartment complexes, construction of non-residential premises, business office builder, commercial builder, commercial premises, warehouse builder",
	DOCTOR: "doctor, GP, practitioner, Hospital, Illness, Drugs, Flu, Children's physician, Doctor's office, waiting room, doctor visit, family doctor, medical doctor, MD, Physician, prescription medication",
	DRIVING_SCHOOL: "driving school,  training of drivers, professional drivers, driving fitness, driving exam, driving school, driving simulator, driving permit",
	ELECTRICIAN_ELECTRICAL_CONTRACTORS: "electrician, electronic contractors, telephone upgrades, VOIP phones, surveillance camera, home security system, office security system, fire systems, electrical installation, electrical service and revision, control and optimization of electrical energy consumption",
	ELECTRONICS_ELECTRICAL_APPLIANCES: "electronics, electrical appliances, electronic components, remote controls, measuring equipment, antennas, coaxial cables, industrial sensors, PLC and CNC control systems, frequency converters, servo drives, EL displays, multimedia, power supplies, DC / DC converters",
	EVENT_PLANNING: "event planning, wedding planning, party planing, Turnkey social events, teambuilding, business parties, receptions, company parties, sports tournaments, wedding reception, retirement party graduation party, conferences, holiday party",
	FAITH_BASED_ORGANIZATIONS: "faith-based organization, Church, non-denomination church, Jesus Christ, salvation, Muslim, Buddhism, helping people, God, Jesus, Christianity, Judaism, Islam",
	FARMERS_MARKETS: "farmers market, small grower, live animals, fresh meats, fresh  milk, eggs, organic farm, organic vegetables, hormone free meat, organic beef, breeding cattle, growing cereal",
	FASHION_CLOTHING_STORE: "fashion store, clothing store, women's fashion, men's fashion, children's fashion, footwear, seasonal clothes, accessories, fashion style, dresses, evening gowns, office wear, party wear",
	FLORIST_FLOWER_SHOP: "florist, flower shop, flowers, bouquets, houseplants, potted flowers, flower arrangements, evergreen flowers, wedding bouquets, exotic flowers, even flower supply",
	FUNERAL_HOMES: "funeral home, funeral service, funeral parlour, cremation and cemetery services, religious ceremonies, obituary, funeral accessories, vases, lamps, ceramic photos, urns",
	FURNITURE_STORE: "furniture store, furniture, sofas, sofa, kitchen dining set, children's rooms, bedrooms, living rooms, chest of drawers, dining room hutch, dining room table, dinning room chairs, king beds, queen beds, dining tables, dining chairs, mattresses, coffee tables",
	GARDENING_LANDSCAPING: "gardening, landscaping, garden design, yard design, gardening, yard care, yard maintenance, tree pruning, irrigation systems, , garden furniture, lawns, ornamental trees, fruit trees, tree planting",
	GENERIC_BUSINESS_TYPE: "marketing, sales, sale, purchase, trade, LLC, distribution, distributor, reseller, business, company",
	GLASS_AND_GLAZING_CONTRACTORS: "glass contractors, glazing contractor, glazier,  sliding doors, glass windows, glass doors, aluminum windows, blinds, window screens, window replacements, glass repair",
	GOODS_TRANSPORTION_HAULING: "goods transportation, hauling, carrier, transportation, trucking, truck deliver, truck driver, transportation service, air freight, sea transport, railroad transport, logistic services, warehousing, customs services",
	GROCER_GROCERY: "grocer, grocery, groceries, food, meats, vegetables, beer, wine, toiletries, prescriptions, prescription refill, pharmaceuticals, toiletries, cosmetics, washing, cleaning products, hygiene",
	GYM_FITNESS_SPORTS_CENTERS: "fitness, recreational sport, sport center, cardio-zone, gym, women's fitness, spinning, aerobics, power yoga, Pilates, kick boxing, fitness class, swimming, workout, massage",
	HARDWARE_STORES: "hardware store, paint, hardware, home repair, home project, home remodel, adhesives, sealants, foams, drills, abrasives, mowers, chainsaws, wheels, stoves, nails, screws, nuts, screwdrivers, hammers, chains",
	HVAC_SERVICES: "heating, ventilation, air conditioning, HVAC, VAC, duct cleaning, AC repair, AC installation, air cleaners, furnace, industrial refrigeration, cooling and freezing equipment",
	HOME_DECOR_ACCESSORIES: "household decor, home decor, decoration, accesories, home accesories, paintings, holiday theme, holiday decoration, bed pillows, bed spreads, bed sets, table cloth, dining set, dishes, pots, pans, kitchen knives",
	HOME_IMPROVEMENT_BUILDING_SUPPLIES: "home improvement, building supplies, gravel, concrete, concrete pits, sewage pipes, masonry, bricks, sand, grit, gravel, concrete products, cement, polystyrene, insulation, doors, drains, roofs, skylights, plasterboard, floor tiles, fireplaces, porch, bathroom remodel, kitchen remodel, tools, blocks",
	HOMEOWNERS_ASSOCIATION: "",
	HOTEL: "hotel, weekend getaway, vacation, weekend packages, resort, weekend trips, family holidays, events, training, congresses, celebrations, social events, parties, banquets",
	HUMAN_RESOURCES: "HR, Human resources, HR solutions, staffing, personnel management",
	INSURANCE_SERVICES: "insurance services, life insurance, auto insurance, personal property insurance, travel insurance, car accident insurance, home insurance, deductible insurance premium, liability insurance",
	INTERIOR_DESIGN_RENOVATIONS: "interior design, office decor, decorations, home decoration, home designer,, home furniture, office furniture, design furniture, kitchen furniture, porcelain, and children's living rooms, bedrooms, atypical interiors, consulting architect, hotel furniture",
	INVESTMENT_ADVISER: "investment adviser, investment advisor, adviser, advisor, insurance and financial advice, college fund, insurance, retirement plans, mortgages, investment management, insurance contracts, brokering mortgages, term deposits, mutual funds",
	IT_CONSULTING_SERVICES: "IT consulting, IT consulting service, computer networks, outsourcing, contracting, computer service, servers, Linux, Microsoft, PC. Apple, camera systems, network security, TECHNICAL support, programming, IT consultant, software application, application development",
	JEWELER: "jeweler, jeweller, gold jewelry, silver jewelry, steel jewelry, jewellery, gold, rings, earrings, bracelets, necklaces, gems, precious stones, men's jewelry,",
	KINDERGARTEN: "kindergarten, school, preschool, nursery, nursery school",
	LAUNDRY_CLEANING_IRONING_SERVICES: "Dry cleaning, laundry, shirts dry-cleaning, laundry, dry cleaning, repair,  pressing, ironing, steaming, Dry Cleaning Express",
	LAW_OFFICE_NOTARY: "law office, notary, legal services, commercial law, incorporation, contracts,  international legal matters, debt collection, arbitration, due diligence, debt collection, acquisitions, mergers",
	LIBRARY: "Library, books, book borrowing, audio library, book rent, newspaper room, reading room",
	LOCKSMITH: "locksmith, opening locks, replacement locks, installing locks, security locks, latch locks, bolt locks, fittings, keys, locksmith",
	CHILDCARE: "childcare, pediatrician, medical services, diagnosis in children, care for premature and at risk children, child counseling, child doctor, treatment of allergies, treatment of immune disorders, inflammation, measles, smallpox, vaccination, child vaccine",
	MOTORCYCLE_SHOP: "motorcycle shop, motorcycle service, motorcycles, motorcycle parts, scooters, motorcycles repair, quads, helmets, tuning center",
	MOVING_STORAGE_SERVICES: "moving services, storage services, moving, Warehouse, storage, storage facility, packing, moving, bubble wrapping, moving boxes, moving supplies",
	NIGHTCLUB_DISCO: "night club, nightclub, disco, dancing, cocktail bar, entertainment, parties, club",
	NON_PROFIT_ORGANIZATIONS: "non-profit organization, social services, social assistance and counseling, cause, not for profit organization, help, social worker, social services",
	OPTICIAN: "optician, prescription glasses, contact lenses, contact lenses, optometrist, eye exam, glasses",
	OTHER_BUSINESS_SERVICES: "accounting, legal, marketing, business consulting, financial planning, business, other business,  service, other service",
	OTHER_EDUCATIONAL_SERVICES: "education, educational service, other education, school, courses, training, schooling, elementary school, high school, vocational school, training certificate, diploma, ",
	PAINTER_PAPERHANGER: "painter, paperhanger, residential painting, home painting, office painting, plaster work, exterior painting, façade painting,  painting rooms, facade painting",
	PET_CARE: "pet grooming, dogs, dog, cat, dog care, pet care, cat care, cats, dog hotel, pet cremation, pet boarding, nail trimming, haircut for dogs",
	PHARMACY: "pharmacy, prescription, medication, prescription filling, medicines, vitamins, cosmetics, blood pressure medication, weight loss treatment, pharmaceuticals, supplements, cosmetics, homeopathy, minerals",
	PHOTOGRAPHY: "photography, photographer, portrait photo, family portrait, photo studio, wedding photo, wedding album, baby pictures, graduation photos, holiday photo, anniversary photo, wedding photos, wedding video, digital photo, film photo, making pictures, passport photos",
	PHYSIOTHERAPIST_MASSEUSE: "Physiotherapist, masseuse, omprehensive physiotherapy, rehabilitation, physical therapy, back pain, chiropractic, physical exercise, massage,  shiatsu, craniofacial therapy, yoga for seniors",
	PLUMBER: "plumber, plumbing work, drainage problem, toilet clog, broken pipe, pipe leak, water leak, faucet installation, frozen pipe, water heater repair",
	PR_MARKETING: "PR, Marketing, public relations, receptions, events, sales support, sales promotion, product launch, marketing campaign, PR, promotional event, spokesperson, press conference, press releases, press materials, brochures, product catalog, leaflets, business cards, direct mail, email campaign, TV spot, radio spot, ad, newspaper ad",
	PRINTING_SERVICES: "printing services, digital printing, graphic design, business cards, sales brochure, marketing brochure, printing, press, event invitations, stickers, billboards, logos, sign making, photocopying and binding",
	REAL_ESTATE: "real estate agent, broker, home sale, lease, real estate development, real estate investor, real estate market analysis, buy land, sale land, buy home, buy house, rent home rent apartment, houses, villas, commercial real estate, property management",
	RESTAURANT: "restaurant, steaks, specialties and menus, family celebrations, weddings, party, Italian cuisine, beer, soft drinks, fast, good wine, good service, great food",
	RETIREMENT_HOMES: "retirement home, seniors housing, senior care, senior home, elderly home, senor accommodation, full board, medical attention for seniors",
	ROOFER: "roofer, roof repair, waterproofing, roof insulation, leak repair, roof reconstruction, assembly walls of windows, shingles repair, roof installation",
	SCHOOL_COLLEGE: "school, college, university, high school classes, advance learning for degrees, bachelor degree, high school diploma, business degree",
	SHOE_STORE: "shoe store, comfortable shoes, summer shoes, winter shoes, boots, sport shoes, shoes for any occasion",
	SPA_BEAUTY: "Beauty salon, spa, sauna, massage, foot massage, sea salt bath, facial, relaxation, wellness program, whirlpool",
	SPORTS_OUTDOOR: "sport equipment store, outdoor store, outdoor, sports complex, soccer, bowling, hockey, squash, tennis, sections, skin and corporate fitness program, climbing center, cycling, volleyball, weight loss activities, running track",
	SPORTS_CLUBS: "sport club, league, association, hockey, squash, tennis, soccer, hiking, fitness, skiing, snowboarding, water sports, basketball, football, golf, sport, bike, skateboard, fitness equipment",
	STATIONERY: "stationery, office supply, printing paper, school supplies, stationary, office supplies, forms, envelopes, calendar, greeting cards, coloring books, writing instruments, pens, ball pens, ink pens, gift sets, games, coloring books",
	TAILORING: "tailoring, alteration services, custom tailor, clothes repairs and modifications branches, curtains and textiles, tailor-made suit, jackets, pants, skirts, shirts",
	TAXI_LIMO: "taxi, taxi service, limo, transportation services, passenger transport, delivery services, don drink and drive, take a cab, cab service, taxi pickup, airport service, airport taxi, party transport",
	TOY_STORE: "toy store, Barbie doll, puzzles, dolls, toys, infant toys, toddler toys, learning games, building blocks,  Lego, robots, baby program",
	TRAVEL: "travel services, tour operator, travel tours, Travel to Europe, travel to Asia, Travel to Mexico, South America, last minute trip, winter tours, vacation, holiday travel",
	VETERINARIANS: "veterinarian, pet ambulance, pet health, vetrinarian's office, dog shots, cat shots, dog medicine, vegetarian, dog breeding",
	WEB_DESIGN: "Web design, web graphic design, authoring, SEO, CSS, HTML, graphic designer, internet copywriter, marketing specialist",
	WEB_DEVELOPMENT: "web development, web applications, web developer, software development, web development, application"
};

Countries.data = {
	af: "Afghanistan",
	al: "Albania",
	dz: "Algeria",
	as: "American Samoa",
	ad: "Andorra",
	ao: "Angola",
	ai: "Anguilla",
	aq: "Antarctica",
	ag: "Antigua and Barbuda",
	ar: "Argentina",
	am: "Armenia",
	aw: "Aruba",
	au: "Australia",
	at: "Austria",
	az: "Azerbaijan",
	bs: "Bahamas",
	bh: "Bahrain",
	bd: "Bangladesh",
	bb: "Barbados",
	by: "Belarus",
	be: "Belgium",
	bz: "Belize",
	bj: "Benin",
	bm: "Bermuda",
	bt: "Bhutan",
	bo: "Bolivia",
	ba: "Bosnia and Herzegovina",
	bw: "Botswana",
	bv: "Bouvet Island",
	br: "Brazil",
	io: "British Indian Ocean Territory",
	vg: "British Virgin Islands",
	bn: "Brunei",
	bg: "Bulgaria",
	bf: "Burkina Faso",
	bi: "Burundi",
	kh: "Cambodia",
	cm: "Cameroon",
	ca: "Canada",
	cv: "Cape Verde",
	ky: "Cayman Islands",
	cf: "Central African Republic",
	td: "Chad",
	cl: "Chile",
	cn: "China",
	cx: "Christmas Island",
	cc: "Cocos [Keeling] Islands",
	co: "Colombia",
	km: "Comoros",
	cg: "Congo [Republic]",
	ck: "Cook Islands",
	cr: "Costa Rica",
	hr: "Croatia",
	cu: "Cuba",
	cy: "Cyprus",
	cz: "Czech Republic",
	dk: "Denmark",
	dj: "Djibouti",
	dm: "Dominica",
	"do": "Dominican Republic",
	ec: "Ecuador",
	eg: "Egypt",
	sv: "El Salvador",
	gq: "Equatorial Guinea",
	ee: "Estonia",
	et: "Ethiopia",
	fk: "Falkland Islands [Islas Malvinas]",
	fo: "Faroe Islands",
	fj: "Fiji",
	fi: "Finland",
	fr: "France",
	gf: "French Guiana",
	pf: "French Polynesia",
	tf: "French Southern Territories",
	ga: "Gabon",
	gm: "Gambia",
	ge: "Georgia",
	de: "Germany",
	gh: "Ghana",
	gi: "Gibraltar",
	gr: "Greece",
	gl: "Greenland",
	gd: "Grenada",
	gp: "Guadeloupe",
	gu: "Guam",
	gt: "Guatemala",
	gn: "Guinea",
	gw: "Guinea-Bissau",
	gy: "Guyana",
	ht: "Haiti",
	hm: "Heard Island and McDonald Islands",
	hn: "Honduras",
	hk: "Hong Kong",
	hu: "Hungary",
	is: "Iceland",
	"in": "India",
	id: "Indonesia",
	ir: "Iran",
	iq: "Iraq",
	ie: "Ireland",
	il: "Israel",
	it: "Italy",
	ci: "Ivory Coast",
	jm: "Jamaica",
	jp: "Japan",
	jo: "Jordan",
	kz: "Kazakhstan",
	ke: "Kenya",
	ki: "Kiribati",
	kw: "Kuwait",
	kg: "Kyrgyzstan",
	la: "Laos",
	lv: "Latvia",
	lb: "Lebanon",
	ls: "Lesotho",
	lr: "Liberia",
	ly: "Libya",
	li: "Liechtenstein",
	lt: "Lithuania",
	lu: "Luxembourg",
	mo: "Macau",
	mk: "Macedonia [FYROM]",
	mg: "Madagascar",
	mw: "Malawi",
	my: "Malaysia",
	mv: "Maldives",
	ml: "Mali",
	mt: "Malta",
	mh: "Marshall Islands",
	mq: "Martinique",
	mr: "Mauritania",
	mu: "Mauritius",
	mx: "Mexico",
	fm: "Micronesia",
	md: "Moldova",
	mc: "Monaco",
	mn: "Mongolia",
	me: "Montenegro",
	ms: "Montserrat",
	ma: "Morocco",
	mz: "Mozambique",
	mm: "Myanmar [Burma]",
	na: "Namibia",
	nr: "Nauru",
	np: "Nepal",
	nl: "Netherlands",
	an: "Netherlands Antilles",
	nc: "New Caledonia",
	nz: "New Zealand",
	ni: "Nicaragua",
	ne: "Niger",
	ng: "Nigeria",
	nu: "Niue",
	nf: "Norfolk Island",
	mp: "Northern Mariana Islands",
	kp: "North Korea",
	no: "Norway",
	om: "Oman",
	pk: "Pakistan",
	pw: "Palau",
	pa: "Panama",
	pg: "Papua New Guinea",
	py: "Paraguay",
	pe: "Peru",
	ph: "Philippines",
	pn: "Pitcairn Islands",
	pl: "Poland",
	pt: "Portugal",
	pr: "Puerto Rico",
	qa: "Qatar",
	re: "R\u00e9union",
	ro: "Romania",
	ru: "Russia",
	rw: "Rwanda",
	sh: "Saint Helena",
	kn: "Saint Kitts and Nevis",
	lc: "Saint Lucia",
	pm: "Saint Pierre and Miquelon",
	vc: "Saint Vincent and the Grenadines",
	ws: "Samoa",
	sm: "San Marino",
	st: "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
	sa: "Saudi Arabia",
	sn: "Senegal",
	rs: "Serbia",
	sc: "Seychelles",
	sl: "Sierra Leone",
	sg: "Singapore",
	sk: "Slovakia",
	si: "Slovenia",
	sb: "Solomon Islands",
	so: "Somalia",
	za: "South Africa",
	kr: "South Korea",
	es: "Spain",
	lk: "Sri Lanka",
	sd: "Sudan",
	sr: "Suriname",
	sj: "Svalbard and Jan Mayen",
	sz: "Swaziland",
	se: "Sweden",
	ch: "Switzerland",
	sy: "Syria",
	tw: "Taiwan",
	tj: "Tajikistan",
	tz: "Tanzania",
	th: "Thailand",
	tg: "Togo",
	tk: "Tokelau",
	to: "Tonga",
	tt: "Trinidad and Tobago",
	tn: "Tunisia",
	tr: "Turkey",
	tm: "Turkmenistan",
	tc: "Turks and Caicos Islands",
	tv: "Tuvalu",
	ug: "Uganda",
	gb: "U.K.",
	ua: "Ukraine",
	ae: "United Arab Emirates",
	uy: "Uruguay",
	us: "U.S.",
	um: "U.S. Outlying Islands",
	vi: "U.S. Virgin Islands",
	uz: "Uzbekistan",
	vu: "Vanuatu",
	va: "Vatican City",
	ve: "Venezuela",
	vn: "Vietnam",
	wf: "Wallis and Futuna",
	eh: "Western Sahara",
	ye: "Yemen",
	zm: "Zambia",
	zw: "Zimbabwe"
};

Countries.currency = {
	aa: 1,
	ad: 3,
	ae: 4,
	af: 5,
	ag: 161,
	ai: 161,
	al: 6,
	am: 7,
	an: 8,
	ao: 9,
	aq: 1,
	ar: 10,
	as: 1,
	at: 3,
	au: 11,
	aw: 12,
	az: 13,
	ba: 14,
	bb: 15,
	bd: 16,
	be: 3,
	bf: 163,
	bg: 17,
	bh: 18,
	bi: 19,
	bj: 163,
	bm: 20,
	bn: 1,
	bo: 22,
	br: 23,
	bs: 24,
	bt: 67,
	bu: 95,
	bv: 1,
	bw: 26,
	by: 27,
	bz: 28,
	ca: 29,
	cc: 11,
	cf: 158,
	cg: 30,
	ch: 63,
	ci: 1,
	ck: 110,
	cl: 31,
	cm: 158,
	cn: 32,
	co: 33,
	cr: 34,
	cu: 36,
	cv: 37,
	cx: 11,
	cy: 3,
	cz: 2,
	de: 3,
	dj: 38,
	dk: 39,
	dm: 161,
	"do": 40,
	dz: 41,
	ec: 1,
	ee: 42,
	eg: 43,
	eh: 91,
	es: 3,
	et: 45,
	fi: 3,
	fj: 46,
	fk: 47,
	fm: 1,
	fo: 39,
	fr: 3,
	ga: 158,
	gb: 48,
	gd: 161,
	ge: 49,
	gf: 3,
	gh: 51,
	gi: 52,
	gl: 39,
	gm: 53,
	gn: 54,
	gp: 3,
	gq: 158,
	gr: 3,
	gt: 55,
	gu: 1,
	gw: 163,
	gy: 56,
	hk: 57,
	hm: 1,
	hn: 58,
	hr: 59,
	ht: 60,
	hu: 61,
	id: 64,
	ie: 3,
	il: 65,
	"in": 67,
	io: 1,
	iq: 68,
	ir: 69,
	is: 70,
	it: 3,
	jm: 72,
	jo: 73,
	jp: 74,
	ke: 75,
	kg: 76,
	kh: 77,
	ki: 11,
	km: 78,
	kn: 161,
	kp: 79,
	kr: 1,
	kw: 80,
	ky: 81,
	kz: 82,
	la: 83,
	lb: 84,
	lc: 161,
	li: 63,
	lk: 85,
	lr: 86,
	ls: 87,
	lt: 88,
	lu: 3,
	lv: 89,
	ly: 90,
	ma: 91,
	mc: 3,
	md: 92,
	me: 3,
	mg: 93,
	mh: 1,
	mk: 94,
	ml: 163,
	mm: 95,
	mn: 96,
	mo: 97,
	mp: 1,
	mq: 3,
	mr: 98,
	ms: 161,
	mt: 3,
	mu: 99,
	mv: 100,
	mw: 101,
	mx: 102,
	my: 103,
	mz: 104,
	na: 105,
	nc: 165,
	ne: 163,
	nf: 11,
	ng: 106,
	ni: 107,
	nl: 3,
	no: 108,
	np: 109,
	nr: 11,
	nt: 1,
	nu: 110,
	nz: 110,
	om: 111,
	pa: 1,
	pe: 113,
	pf: 165,
	pg: 114,
	ph: 115,
	pk: 116,
	pl: 117,
	pm: 3,
	pn: 110,
	pr: 1,
	pt: 3,
	pw: 1,
	py: 118,
	qa: 119,
	re: 1,
	ro: 120,
	rs: 121,
	ru: 122,
	rw: 123,
	sa: 124,
	sb: 125,
	sc: 126,
	sd: 127,
	se: 128,
	sg: 129,
	sh: 130,
	si: 3,
	sj: 1,
	sk: 3,
	sl: 132,
	sm: 3,
	sn: 163,
	so: 133,
	sr: 135,
	st: 136,
	sv: 1,
	sy: 138,
	sz: 169,
	tc: 1,
	td: 158,
	tf: 3,
	tg: 163,
	th: 140,
	tj: 141,
	tk: 110,
	tm: 142,
	tn: 143,
	to: 144,
	tp: 1,
	tr: 145,
	tt: 146,
	tv: 147,
	tw: 148,
	tz: 149,
	ua: 150,
	ug: 151,
	um: 1,
	us: 1,
	uy: 152,
	uz: 153,
	va: 3,
	vc: 161,
	ve: 154,
	vg: 1,
	vi: 1,
	vn: 155,
	vu: 156,
	wf: 165,
	ws: 157,
	ye: 167,
	yu: 1,
	za: 168,
	zm: 170,
	zr: 1,
	zw: 171
};

CountriesWithUS.data = {
	af: "Afghanistan",
	al: "Albania",
	dz: "Algeria",
	as: "American Samoa",
	ad: "Andorra",
	ao: "Angola",
	ai: "Anguilla",
	aq: "Antarctica",
	ag: "Antigua and Barbuda",
	ar: "Argentina",
	am: "Armenia",
	aw: "Aruba",
	au: "Australia",
	at: "Austria",
	az: "Azerbaijan",
	bs: "Bahamas",
	bh: "Bahrain",
	bd: "Bangladesh",
	bb: "Barbados",
	by: "Belarus",
	be: "Belgium",
	bz: "Belize",
	bj: "Benin",
	bm: "Bermuda",
	bt: "Bhutan",
	bo: "Bolivia",
	ba: "Bosnia and Herzegovina",
	bw: "Botswana",
	bv: "Bouvet Island",
	br: "Brazil",
	io: "British Indian Ocean Territory",
	vg: "British Virgin Islands",
	bn: "Brunei",
	bg: "Bulgaria",
	bf: "Burkina Faso",
	bi: "Burundi",
	kh: "Cambodia",
	cm: "Cameroon",
	ca: "Canada",
	cv: "Cape Verde",
	ky: "Cayman Islands",
	cf: "Central African Republic",
	td: "Chad",
	cl: "Chile",
	cn: "China",
	cx: "Christmas Island",
	cc: "Cocos [Keeling] Islands",
	co: "Colombia",
	km: "Comoros",
	cg: "Congo [Republic]",
	ck: "Cook Islands",
	cr: "Costa Rica",
	hr: "Croatia",
	cu: "Cuba",
	cy: "Cyprus",
	cz: "Czech Republic",
	dk: "Denmark",
	dj: "Djibouti",
	dm: "Dominica",
	"do": "Dominican Republic",
	ec: "Ecuador",
	eg: "Egypt",
	sv: "El Salvador",
	gq: "Equatorial Guinea",
	ee: "Estonia",
	et: "Ethiopia",
	fk: "Falkland Islands [Islas Malvinas]",
	fo: "Faroe Islands",
	fj: "Fiji",
	fi: "Finland",
	fr: "France",
	gf: "French Guiana",
	pf: "French Polynesia",
	tf: "French Southern Territories",
	ga: "Gabon",
	gm: "Gambia",
	ge: "Georgia",
	de: "Germany",
	gh: "Ghana",
	gi: "Gibraltar",
	gr: "Greece",
	gl: "Greenland",
	gd: "Grenada",
	gp: "Guadeloupe",
	gu: "Guam",
	gt: "Guatemala",
	gn: "Guinea",
	gw: "Guinea-Bissau",
	gy: "Guyana",
	ht: "Haiti",
	hm: "Heard Island and McDonald Islands",
	hn: "Honduras",
	hk: "Hong Kong",
	hu: "Hungary",
	is: "Iceland",
	"in": "India",
	id: "Indonesia",
	ir: "Iran",
	iq: "Iraq",
	ie: "Ireland",
	il: "Israel",
	it: "Italy",
	ci: "Ivory Coast",
	jm: "Jamaica",
	jp: "Japan",
	jo: "Jordan",
	kz: "Kazakhstan",
	ke: "Kenya",
	ki: "Kiribati",
	kw: "Kuwait",
	kg: "Kyrgyzstan",
	la: "Laos",
	lv: "Latvia",
	lb: "Lebanon",
	ls: "Lesotho",
	lr: "Liberia",
	ly: "Libya",
	li: "Liechtenstein",
	lt: "Lithuania",
	lu: "Luxembourg",
	mo: "Macau",
	mk: "Macedonia [FYROM]",
	mg: "Madagascar",
	mw: "Malawi",
	my: "Malaysia",
	mv: "Maldives",
	ml: "Mali",
	mt: "Malta",
	mh: "Marshall Islands",
	mq: "Martinique",
	mr: "Mauritania",
	mu: "Mauritius",
	mx: "Mexico",
	fm: "Micronesia",
	md: "Moldova",
	mc: "Monaco",
	mn: "Mongolia",
	me: "Montenegro",
	ms: "Montserrat",
	ma: "Morocco",
	mz: "Mozambique",
	mm: "Myanmar [Burma]",
	na: "Namibia",
	nr: "Nauru",
	np: "Nepal",
	nl: "Netherlands",
	an: "Netherlands Antilles",
	nc: "New Caledonia",
	nz: "New Zealand",
	ni: "Nicaragua",
	ne: "Niger",
	ng: "Nigeria",
	nu: "Niue",
	nf: "Norfolk Island",
	mp: "Northern Mariana Islands",
	kp: "North Korea",
	no: "Norway",
	om: "Oman",
	pk: "Pakistan",
	pw: "Palau",
	pa: "Panama",
	pg: "Papua New Guinea",
	py: "Paraguay",
	pe: "Peru",
	ph: "Philippines",
	pn: "Pitcairn Islands",
	pl: "Poland",
	pt: "Portugal",
	pr: "Puerto Rico",
	qa: "Qatar",
	re: "R\u00e9union",
	ro: "Romania",
	ru: "Russia",
	rw: "Rwanda",
	sh: "Saint Helena",
	kn: "Saint Kitts and Nevis",
	lc: "Saint Lucia",
	pm: "Saint Pierre and Miquelon",
	vc: "Saint Vincent and the Grenadines",
	ws: "Samoa",
	sm: "San Marino",
	st: "S\u00e3o Tom\u00e9 and Pr\u00edncipe",
	sa: "Saudi Arabia",
	sn: "Senegal",
	rs: "Serbia",
	sc: "Seychelles",
	sl: "Sierra Leone",
	sg: "Singapore",
	sk: "Slovakia",
	si: "Slovenia",
	sb: "Solomon Islands",
	so: "Somalia",
	za: "South Africa",
	kr: "South Korea",
	es: "Spain",
	lk: "Sri Lanka",
	sd: "Sudan",
	sr: "Suriname",
	sj: "Svalbard and Jan Mayen",
	sz: "Swaziland",
	se: "Sweden",
	ch: "Switzerland",
	sy: "Syria",
	tw: "Taiwan",
	tj: "Tajikistan",
	tz: "Tanzania",
	th: "Thailand",
	tg: "Togo",
	tk: "Tokelau",
	to: "Tonga",
	tt: "Trinidad and Tobago",
	tn: "Tunisia",
	tr: "Turkey",
	tm: "Turkmenistan",
	tc: "Turks and Caicos Islands",
	tv: "Tuvalu",
	ug: "Uganda",
	gb: "U.K.",
	ua: "Ukraine",
	ae: "United Arab Emirates",
	uy: "Uruguay",
	us: "U.S.",
	um: "U.S. Outlying Islands",
	vi: "U.S. Virgin Islands",
	uz: "Uzbekistan",
	vu: "Vanuatu",
	va: "Vatican City",
	ve: "Venezuela",
	vn: "Vietnam",
	wf: "Wallis and Futuna",
	eh: "Western Sahara",
	ye: "Yemen",
	zm: "Zambia",
	zw: "Zimbabwe"
};

CountriesWithUS.currency = {
	aa: 1,
	ad: 3,
	ae: 4,
	af: 5,
	ag: 161,
	ai: 161,
	al: 6,
	am: 7,
	an: 8,
	ao: 9,
	aq: 1,
	ar: 10,
	as: 1,
	at: 3,
	au: 11,
	aw: 12,
	az: 13,
	ba: 14,
	bb: 15,
	bd: 16,
	be: 3,
	bf: 163,
	bg: 17,
	bh: 18,
	bi: 19,
	bj: 163,
	bm: 20,
	bn: 1,
	bo: 22,
	br: 23,
	bs: 24,
	bt: 67,
	bu: 95,
	bv: 1,
	bw: 26,
	by: 27,
	bz: 28,
	ca: 29,
	cc: 11,
	cf: 158,
	cg: 30,
	ch: 63,
	ci: 1,
	ck: 110,
	cl: 31,
	cm: 158,
	cn: 32,
	co: 33,
	cr: 34,
	cu: 36,
	cv: 37,
	cx: 11,
	cy: 3,
	cz: 2,
	de: 3,
	dj: 38,
	dk: 39,
	dm: 161,
	"do": 40,
	dz: 41,
	ec: 1,
	ee: 42,
	eg: 43,
	eh: 91,
	es: 3,
	et: 45,
	fi: 3,
	fj: 46,
	fk: 47,
	fm: 1,
	fo: 39,
	fr: 3,
	ga: 158,
	gb: 48,
	gd: 161,
	ge: 49,
	gf: 3,
	gh: 51,
	gi: 52,
	gl: 39,
	gm: 53,
	gn: 54,
	gp: 3,
	gq: 158,
	gr: 3,
	gt: 55,
	gu: 1,
	gw: 163,
	gy: 56,
	hk: 57,
	hm: 1,
	hn: 58,
	hr: 59,
	ht: 60,
	hu: 61,
	id: 64,
	ie: 3,
	il: 65,
	"in": 67,
	io: 1,
	iq: 68,
	ir: 69,
	is: 70,
	it: 3,
	jm: 72,
	jo: 73,
	jp: 74,
	ke: 75,
	kg: 76,
	kh: 77,
	ki: 11,
	km: 78,
	kn: 161,
	kp: 79,
	kr: 1,
	kw: 80,
	ky: 81,
	kz: 82,
	la: 83,
	lb: 84,
	lc: 161,
	li: 63,
	lk: 85,
	lr: 86,
	ls: 87,
	lt: 88,
	lu: 3,
	lv: 89,
	ly: 90,
	ma: 91,
	mc: 3,
	md: 92,
	me: 3,
	mg: 93,
	mh: 1,
	mk: 94,
	ml: 163,
	mm: 95,
	mn: 96,
	mo: 97,
	mp: 1,
	mq: 3,
	mr: 98,
	ms: 161,
	mt: 3,
	mu: 99,
	mv: 100,
	mw: 101,
	mx: 102,
	my: 103,
	mz: 104,
	na: 105,
	nc: 165,
	ne: 163,
	nf: 11,
	ng: 106,
	ni: 107,
	nl: 3,
	no: 108,
	np: 109,
	nr: 11,
	nt: 1,
	nu: 110,
	nz: 110,
	om: 111,
	pa: 1,
	pe: 113,
	pf: 165,
	pg: 114,
	ph: 115,
	pk: 116,
	pl: 117,
	pm: 3,
	pn: 110,
	pr: 1,
	pt: 3,
	pw: 1,
	py: 118,
	qa: 119,
	re: 1,
	ro: 120,
	rs: 121,
	ru: 122,
	rw: 123,
	sa: 124,
	sb: 125,
	sc: 126,
	sd: 127,
	se: 128,
	sg: 129,
	sh: 130,
	si: 3,
	sj: 1,
	sk: 3,
	sl: 132,
	sm: 3,
	sn: 163,
	so: 133,
	sr: 135,
	st: 136,
	sv: 1,
	sy: 138,
	sz: 169,
	tc: 1,
	td: 158,
	tf: 3,
	tg: 163,
	th: 140,
	tj: 141,
	tk: 110,
	tm: 142,
	tn: 143,
	to: 144,
	tp: 1,
	tr: 145,
	tt: 146,
	tv: 147,
	tw: 148,
	tz: 149,
	ua: 150,
	ug: 151,
	um: 1,
	us: 1,
	uy: 152,
	uz: 153,
	va: 3,
	vc: 161,
	ve: 154,
	vg: 1,
	vi: 1,
	vn: 155,
	vu: 156,
	wf: 165,
	ws: 157,
	ye: 167,
	yu: 1,
	za: 168,
	zm: 170,
	zr: 1,
	zw: 171
};

UnitedStates.data = {
	1: "Alabama",
	2: "Alaska",
	3: "Arizona",
	4: "Arkansas",
	5: "California",
	6: "Colorado",
	7: "Connecticut",
	8: "Delaware",
	9: "Florida",
	10: "Georgia",
	11: "Hawaii",
	12: "Idaho",
	13: "Illinois",
	14: "Indiana",
	15: "Iowa",
	16: "Kansas",
	17: "Kentucky",
	18: "Louisiana",
	19: "Maine",
	20: "Maryland",
	21: "Massachusetts",
	22: "Michigan",
	23: "Minnesota",
	24: "Mississipi",
	25: "Missouri",
	26: "Montana",
	27: "Nebraska",
	28: "Nevada",
	29: "New Hampshire",
	30: "New Jersey",
	31: "New Mexico",
	32: "New York",
	33: "North Carolina",
	34: "North Dakota",
	35: "Ohio",
	36: "Oklahoma",
	37: "Oregon",
	38: "Pennsylvania",
	39: "Rhode Island",
	40: "South Carolina",
	41: "South Dakota",
	42: "Tennessee",
	43: "Texas",
	44: "Utah",
	45: "Vermont",
	46: "Virginia",
	47: "Washington",
	48: "West Virginia",
	49: "Wisconsin",
	50: "Wyoming"
};

Currencies.data = {
	_5: "Afghan Afghani (AFN)",
	_6: "Albanian Lek (ALL)",
	_41: "Algerian Dinar (DZD)",
	_9: "Angolan Kwanza (AOA)",
	_10: "Argentine Peso (ARS)",
	_7: "Armenian Dram (AMD)",
	_12: "Aruban Florin (AWG)",
	_11: "Australian Dollar (AUD)",
	_13: "Azerbaijani Manat (AZN)",
	_24: "Bahamian Dollar (BSD)",
	_18: "Bahraini Dinar (BHD)",
	_16: "Bangladeshi Taka (BDT)",
	_15: "Barbadian Dollar (BBD)",
	_27: "Belarusian Ruble (BYR)",
	_28: "Belize Dollar (BZD)",
	_20: "Bermudan Dollar (BMD)",
	_25: "Bhutanese Ngultrum (BTN)",
	_22: "Bolivian Boliviano (BOB)",
	_14: "Bosnia-Herzegovina Convertible Mark (BAM)",
	_26: "Botswanan Pula (BWP)",
	_23: "Brazilian Real (BRL)",
	_48: "British Pound Sterling (GBP)",
	_21: "Brunei Dollar (BND)",
	_17: "Bulgarian Lev (BGN)",
	_19: "Burundian Franc (BIF)",
	_77: "Cambodian Riel (KHR)",
	_29: "Canadian Dollar (CAD)",
	_37: "Cape Verdean Escudo (CVE)",
	_81: "Cayman Islands Dollar (KYD)",
	_163: "CFA Franc BCEAO (XOF)",
	_158: "CFA Franc BEAC (XAF)",
	_165: "CFP Franc (XPF)",
	_31: "Chilean Peso (CLP)",
	_32: "Chinese Yuan (CNY)",
	_33: "Colombian Peso (COP)",
	_78: "Comorian Franc (KMF)",
	_30: "Congolese Franc (CDF)",
	_34: "Costa Rican Col\u00f3n (CRC)",
	_59: "Croatian Kuna (HRK)",
	_35: "Cuban Convertible Peso (CUC)",
	_36: "Cuban Peso (CUP)",
	_2: "Czech Republic Koruna (CZK)",
	_39: "Danish Krone (DKK)",
	_38: "Djiboutian Franc (DJF)",
	_40: "Dominican Peso (DOP)",
	_161: "East Caribbean Dollar (XCD)",
	_43: "Egyptian Pound (EGP)",
	_44: "Eritrean Nakfa (ERN)",
	_45: "Ethiopian Birr (ETB)",
	_3: "Euro (EUR)",
	_47: "Falkland Islands Pound (FKP)",
	_46: "Fijian Dollar (FJD)",
	_53: "Gambian Dalasi (GMD)",
	_49: "Georgian Lari (GEL)",
	_51: "Ghanaian Cedi (GHS)",
	_52: "Gibraltar Pound (GIP)",
	_55: "Guatemalan Quetzal (GTQ)",
	_54: "Guinean Franc (GNF)",
	_56: "Guyanaese Dollar (GYD)",
	_60: "Haitian Gourde (HTG)",
	_58: "Honduran Lempira (HNL)",
	_57: "Hong Kong Dollar (HKD)",
	_61: "Hungarian Forint (HUF)",
	_70: "Icelandic Kr\u00f3na (ISK)",
	_67: "Indian Rupee (INR)",
	_64: "Indonesian Rupiah (IDR)",
	_69: "Iranian Rial (IRR)",
	_68: "Iraqi Dinar (IQD)",
	_65: "Israeli New Sheqel (ILS)",
	_72: "Jamaican Dollar (JMD)",
	_74: "Japanese Yen (JPY)",
	_73: "Jordanian Dinar (JOD)",
	_82: "Kazakhstani Tenge (KZT)",
	_75: "Kenyan Shilling (KES)",
	_80: "Kuwaiti Dinar (KWD)",
	_76: "Kyrgystani Som (KGS)",
	_83: "Laotian Kip (LAK)",
	_89: "Latvian Lats (LVL)",
	_84: "Lebanese Pound (LBP)",
	_87: "Lesotho Loti (LSL)",
	_86: "Liberian Dollar (LRD)",
	_90: "Libyan Dinar (LYD)",
	_88: "Lithuanian Litas (LTL)",
	_97: "Macanese Pataca (MOP)",
	_94: "Macedonian Denar (MKD)",
	_93: "Malagasy Ariary (MGA)",
	_101: "Malawian Kwacha (MWK)",
	_103: "Malaysian Ringgit (MYR)",
	_100: "Maldivian Rufiyaa (MVR)",
	_98: "Mauritanian Ouguiya (MRO)",
	_99: "Mauritian Rupee (MUR)",
	_102: "Mexican Peso (MXN)",
	_92: "Moldovan Leu (MDL)",
	_96: "Mongolian Tugrik (MNT)",
	_91: "Moroccan Dirham (MAD)",
	_104: "Mozambican Metical (MZN)",
	_95: "Myanma Kyat (MMK)",
	_105: "Namibian Dollar (NAD)",
	_109: "Nepalese Rupee (NPR)",
	_8: "Netherlands Antillean Guilder (ANG)",
	_148: "New Taiwan Dollar (TWD)",
	_110: "New Zealand Dollar (NZD)",
	_107: "Nicaraguan C\u00f3rdoba (NIO)",
	_106: "Nigerian Naira (NGN)",
	_108: "Norwegian Krone (NOK)",
	_111: "Omani Rial (OMR)",
	_116: "Pakistani Rupee (PKR)",
	_112: "Panamanian Balboa (PAB)",
	_114: "Papua New Guinean Kina (PGK)",
	_118: "Paraguayan Guarani (PYG)",
	_113: "Peruvian Nuevo Sol (PEN)",
	_115: "Philippine Peso (PHP)",
	_117: "Polish Zloty (PLN)",
	_119: "Qatari Rial (QAR)",
	_120: "Romanian Leu (RON)",
	_122: "Russian Ruble (RUB)",
	_123: "Rwandan Franc (RWF)",
	_130: "Saint Helena Pound (SHP)",
	_157: "Samoan Tala (WST)",
	_136: "S\u00e3o Tom\u00e9 and Pr\u00edncipe Dobra (STD)",
	_124: "Saudi Riyal (SAR)",
	_121: "Serbian Dinar (RSD)",
	_126: "Seychellois Rupee (SCR)",
	_132: "Sierra Leonean Leone (SLL)",
	_129: "Singapore Dollar (SGD)",
	_125: "Solomon Islands Dollar (SBD)",
	_133: "Somali Shilling (SOS)",
	_168: "South African Rand (ZAR)",
	_172: "South Korean Won (KRW)",
	_85: "Sri Lankan Rupee (LKR)",
	_127: "Sudanese Pound (SDG)",
	_135: "Surinamese Dollar (SRD)",
	_139: "Swazi Lilangeni (SZL)",
	_128: "Swedish Krona (SEK)",
	_63: "Swiss Franc (CHF)",
	_138: "Syrian Pound (SYP)",
	_141: "Tajikistani Somoni (TJS)",
	_149: "Tanzanian Shilling (TZS)",
	_140: "Thai Baht (THB)",
	_144: "Tongan Pa\u02bbanga (TOP)",
	_146: "Trinidad and Tobago Dollar (TTD)",
	_143: "Tunisian Dinar (TND)",
	_145: "Turkish Lira (TRY)",
	_142: "Turkmenistani Manat (TMT)",
	_151: "Ugandan Shilling (UGX)",
	_150: "Ukrainian Hryvnia (UAH)",
	_4: "United Arab Emirates Dirham (AED)",
	_152: "Uruguayan Peso (UYU)",
	_1: "US Dollar (USD)",
	_153: "Uzbekistan Som (UZS)",
	_156: "Vanuatu Vatu (VUV)",
	_154: "Venezuelan Bol\u00edvar (VEF)",
	_155: "Vietnamese Dong (VND)",
	_167: "Yemeni Rial (YER)",
	_170: "Zambian Kwacha (ZMW)"
};

Pages.data = {
	web: {
		general: [{
			identifier: "aboutUs",
			title: "About Us",
			selected: "1"
		},
		{
			identifier: "contact",
			title: "Contact Us",
			selected: "1"
		},
		{
			identifier: "news",
			title: "News",
			selected: "1"
		},
		{
			identifier: "photogallery",
			title: "Photogallery",
			selected: "1"
		},
		{
			identifier: "guestbook",
			title: "Guestbook",
			selected: ""
		}],
		advanced: [{
			identifier: "blog",
			title: "Blog",
			selected: ""
		},
		{
			identifier: "products",
			title: "Products",
			selected: ""
		},
		{
			identifier: "ourTeam",
			title: "Our Team",
			selected: ""
		},
		{
			identifier: "faq",
			title: "FAQ",
			selected: ""
		},
		{
			identifier: "eventsCalendar",
			title: "Events Calendar",
			selected: ""
		}]
	},
	
	eshop: {
		general: [{
			identifier: "aboutUs",
			title: "About Us",
			selected: "1"
		},
		{
			identifier: "contact",
			title: "Contact Us",
			selected: "1"
		},
		{
			identifier: "newsEshop",
			title: "News",
			selected: "1"
		}],
		advanced: [{
			identifier: "eshopOurTeam",
			title: "Our Team",
			selected: ""
		},
		{
			identifier: "faq",
			title: "FAQ",
			selected: ""
		},
		{
			identifier: "termsConditions",
			title: "Terms and conditions",
			selected: ""
		},
		{
			identifier: "help",
			title: "Help",
			selected: ""
		}]
	},
	
	branch: {
		general: [{
			identifier: "branch_aboutUs",
			title: "About us",
			selected: "1"
		},
		{
			identifier: "branch_ourServices",
			title: "Services",
			selected: "1"
		},
		{
			identifier: "branch_subpage1",
			title: "Service #1",
			selected: "1"
		},
		{
			identifier: "branch_subpage2",
			title: "Service #2",
			selected: "1"
		},
		{
			identifier: "branch_news",
			title: "News",
			selected: "1"
		},
		{
			identifier: "branch_contact",
			title: "Contact",
			selected: "1"
		}],
		advanced: []
	}
};

Layouts.data.items = {
		//ESHOP
		layoutId50000568: {
			id: 50000568,
			//demo: "http://freemobiweb.mobi/daquy",
			module: "eshop",
			premium: "0",
			preview: {
				src: "50021021-27eac27f09-e-comment.jpg",
				width: 149,
				height: 134
			}
		},
		layoutId50000567: {
			id: 50000567,
			//demo: "http://freemobiweb.mobi/daquy",
			module: "eshop",
			premium: "0",
			preview: {
				src: "50021021-27eac27f09-quanao.jpg",
				width: 149,
				height: 134
			}
		},
		layoutId50000566: {
			id: 50000566,
			//demo: "http://freemobiweb.mobi/daquy",
			module: "eshop",
			premium: "0",
			preview: {
				src: "50021016-19ebf19f18-daquy.png",
				width: 149,
				height: 134
			}
		},	
	layoutId50000565: {
		id: 50000565,
		//demo: "http://freemobiweb.mobi/bepga",
		module: "eshop",
		premium: "0",
		preview: {
			src: "50021021-27eac27f09-bega.png",
			width: 149,
			height: 134
		}
	},
	//WEB
	layoutId50000126: {
		id: 50000126,
		module: "web",
		premium: "0",
		preview: {
			src: "50018978-d9baeda765-rubicus-bolg-1.jpg",
			width: 149,
			height: 113
		}
	},
	
	layoutId50000125: {
		id: 50000125,
		module: "web",
		premium: "0",
		preview: {
			src: "50018974-4207a42847-rubicus-blog-2.jpg",
			width: 149,
			height: 113
		}
	},
	
	layoutId50000124: {
		id: 50000124,
		module: "web",
		premium: "0",
		preview: {
			src: "50018970-004ee00cbb-rubicus-blog-3.jpg",
			width: 149,
			height: 113
		}
	},
	
	layoutId50000123: {
		id: 50000123,
		module: "web",
		premium: "0",
		preview: {
			src: "50018966-3a1723a940-rubicus-blog-4.jpg",
			width: 149,
			height: 113
		}
	},
	/*
	layoutId50000122: {
		id: 50000122,
		module: "web",
		premium: "0",
		preview: {
			src: "50018962-baf5ebb72d-rubicus-blog-5.jpg",
			width: 149,
			height: 113
		}
	},
	
	layoutId50000121: {
		id: 50000121,
		module: "web",
		premium: "0",
		preview: {
			src: "50018255-f2037f2806-rubicus-blog-6.jpg",
			width: 149,
			height: 126
		}
	},
	
	layoutId50000120: {
		id: 50000120,
		module: "web",
		premium: "0",
		preview: {
			src: "50018250-4dde54e5b2-rubicus-blog-7.jpg",
			width: 149,
			height: 127
		}
	},
	
	layoutId50000119: {
		id: 50000119,
		module: "web",
		premium: "0",
		preview: {
			src: "50018245-2682226fef-rubicus-blog-8.jpg",
			width: 149,
			height: 128
		}
	},
	
	layoutId50000118: {
		id: 50000118,
		module: "web",
		premium: "0",
		preview: {
			src: "50018240-74cb875486-rubicu-blog-9.jpg",
			width: 149,
			height: 120
		}
	},
	
	*/
	layoutId50001352: {
		id: 50001352,
		module: "branch",
		premium: "1",
		preview: {
			src: "50022486-29db029e01-rubicus.jpg",
			width: 149,
			height: 134
		}
	},
	
	layoutId50001351: {
		id: 50001351,
		module: "branch",
		premium: "1",
		preview: {
			src: "50023251-2bfab2c001-preview_light_orange.jpg",
			width: 149,
			height: 134
		}
	},
	
	layoutId50001350: {
		id: 50001350,
		module: "branch",
		premium: "1",
		preview: {
			src: "50020657-1cb801d34d-rubicus.jpg",
			width: 149,
			height: 134
		}
	},
	

};

Layouts.data.typesItems = {
	eshop: [50000568,50000567,50000566,50000565,50000564, 50000563 /*, 50000562, 50000561, 50000560, 50000559, 50000558, 50000557, 50000556, 50000555, 50000554, 50000553, 50000552, 50000551, 50000550, 50000549, 50000548, 50000547, 50000546, 50000545, 50000544, 50000543, 50000117, 50000116, 50000115, 50000114, 50000113, 50000112, 50000111, 50000110, 50000109, 50000108, 50000107, 50000106, 50000105, 50000104, 50000103, 50000102, 50000101, 50000100, 50001011, 50001010, 50001009, 50001008, 50001007, 50001006, 50001005, 50001004, 50001003, 50001002, 50001001, 50001000, 50000999, 50000998, 50000997, 50000996, 50000995, 50000994, 50000993, 50001019, 50001018, 50001017, 50001016, 50001015, 50001014, 50001013, 50001012, 50001042, 50001041, 50001040, 50001039, 50001038, 50001037, 50001036, 50001035, 50001034, 50001033, 50001121, 50001120, 50001119, 50001118, 50001117, 50001116, 50001115, 50001114 */],
	web: [50000126, 50000125, 50000124, 50000123, 50000122, 50000121, 50000120, 50000119 /*, 50000118, 50000024, 50000023, 50000022, 50000021, 50000020, 50000019, 50000038, 50000037, 50000036, 50000035, 50000034, 50000033, 50000018, 50000017, 50000016, 50000015, 50000014, 50000013, 50000012, 50000011, 50000010, 50000009, 50000042, 50000041, 50000040, 50000039, 50000032, 50000031, 50000030, 50000029, 50000028, 50000027, 50000026, 50000008, 50000007, 50000006, 50000005, 50000004, 50000003, 50000002, 50000541, 50000540, 50000539, 50000538, 50000537, 50000536, 50000797, 50000796, 50000795, 50000794, 50000793, 50000792, 50000791, 50000535, 50000534, 50000533, 50000532, 50000531, 50000530, 50000529, 50000520, 50000519, 50000518, 50000517, 50000516, 50000515, 50000514, 50000513, 50000512, 50000511, 50000510, 50000528, 50000527, 50000526, 50000525, 50000524, 50000523, 50000522, 50000521, 50000923, 50000922, 50000921, 50000920, 50000919, 50000918, 50000917, 50000916, 50000931, 50000930, 50000929, 50000928, 50000927, 50000926, 50000925, 50000924, 50000953, 50000952, 50000951, 50000950, 50000949, 50000948, 50000947, 50000946, 50000944, 50000943, 50000942, 50000941, 50000940, 50000939, 50000938, 50000937, 50000936, 50000935, 50000934, 50000933, 50000932, 50000964, 50000963, 50000962, 50000961, 50000960, 50000959, 50000958, 50000957, 50000956, 50000955, 50000954, 50000992, 50000991, 50000990, 50000989, 50000988, 50000987, 50000986, 50000985, 50001050, 50001049, 50001048, 50001047, 50001046, 50001045, 50001044, 50001043, 50001059, 50001058, 50001057, 50001056, 50001055, 50001054, 50001053, 50001052, 50001051, 50001083, 50001082, 50001081, 50001080, 50001079, 50001078, 50001077, 50001076, 50001093, 50001092, 50001091, 50001090, 50001089, 50001088, 50001087, 50001086, 50001085, 50001084, 50001075, 50001074, 50001073, 50001072, 50001071, 50001070, 50001099, 50001098, 50001097, 50001096, 50001095, 50001094, 50001105, 50001104, 50001103, 50001102, 50001101, 50001100, 50001129, 50001128, 50001127, 50001126, 50001125, 50001124, 50001123, 50001122, 50001113, 50001112, 50001111, 50001110, 50001109, 50001108, 50001107, 50001106, 50001403, 50001402, 50001401, 50001400, 50001399, 50001398, 50001397, 50001396, 50001395, 50001394, 50001413, 50001412, 50001411, 50001410, 50001409, 50001408, 50001407, 50001406, 50001405, 50001404, 50001447, 50001446, 50001445, 50001444, 50001443, 50001442 */ ],
	//WEB_DEVELOPMENT: [50001352, 50001351,50001350 /*, 50000469, 50000420, 50000419, 50000806, 50000805, 50000395*/],
	branch:[50001352, 50001351,50001350],
	
};


Layouts.data.basicGroupsItems = {
	// eshop
	50000568: 50000045,	
	50000567: 50000045,	
	50000566: 50000045,	
    50000565: 50000045,
	//web
	50000126: 50000012,
	50000125: 50000012,
	50000124: 50000012,
	50000123: 50000012,
	/*50000122: 50000012,
	50000121: 50000011,
	50000120: 50000011,
	50000119: 50000011,
	50000118: 50000011,
	*/
	//brand
	50001352: 50000138,
	50001351: 50000138,
	50001350: 50000138,
	
};

//Layouts.previewLink = "http://static-cdn4.webnode.com/_system/_filesystem/_skins/";
Layouts.previewLink = "http://freemobiweb.mobi/_skins/";
Languages.data = {
	af: "Afrikaans",
	"en-us": "American English",
	az: "Azərbaycan",
	id: "Bahasa Indonesia",
	ms: "Bahasa Melayu",
	jv: "Basa Jawa",
	bs: "Bosanski",
	ca: "Català",
	cz: "Čeština",
	da: "Dansk",
	de: "Deutsch",
	et: "Eesti keel",
	en: "English",
	es: "Español",
	eo: "Esperanto",
	eu: "Euskara",
	fr: "Français",
	hr: "Hrvatski",
	it: "Italiano",
	lv: "Latviešu Valoda",
	lt: "Lietuvių kalba",
	hu: "Magyar",
	nl: "Nederlands",
	no: "Norsk",
	pl: "Polski",
	pt: "Português",
	"pt-br": "Português brasileiro",
	ro: "Română",
	sq: "Shqip",
	sk: "Slovenčina",
	sl: "Slovenski",
	sr: "Srpski",
	fi: "Suomi",
	sv: "Svenska",
	vi: "Tiếng Việt",
	tr: "Türkçe",
	el: "Ελληνικά",
	bg: "Български",
	mk: "Македонски јазик",
	ru: "Русский",
	uk: "Українська",
	he: "עִבְרִית",
	ar: "العربية",
	sd: "سنڌي",
	fa: "فارسی",
	ps: "پښتو",
	mr: "मराठी",
	bh: "मैथिली",
	hi: "हिन्दी",
	bn: "বাংলা",
	pu: "ਪੰਜਾਬੀ",
	gu: "ગુજરાતી",
	or: "ଓଡ଼ିଆ",
	ta: "தமிழ்",
	te: "తెలుగు",
	kn: "ಕನ್ನಡ",
	ml: "മലയാളം",
	th: "ภาษาไทย",
	"zh-tw": "中文 (繁體)",
	"zh-cn": "中文（简体）",
	ja: "日本語",
	ko: "한국어"
};